### ISSUE TITLE
non-existent support for XP

### ISSUE THREAD

**Issue by andika207** [notsonormal/AstoundingDock#3]
this tool doesn't support Windows XP as mentioned in the description.
hope you solve this.

**Comment by notsonormal** [comment]
It would be hard to fix it for Windows XP since I don't have that OS installed anyway. 

You could try version 1.1.1.0. Although I think I started trying to fix windows 10 issues in that release so it might have caused it to break for Windows XP.

https://github.com/notsonormal/AstoundingDock/tree/master/src/AstoundingDock/Setup

The version on Cnet is 1.0.2, this probably works? I forget when I stopped using a Windows XP machine.

 https://download.cnet.com/Astounding-Dock/3000-2344_4-75810702.html
